version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - cd frontend && npm install && cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Node.js code...
      - npm run build
      - echo Building the React app...
      - cd frontend && npm run build && cd ..

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
