name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Use the version of Node.js that you're using in your project

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Install ESLint dependencies
      run: |
        cd backend
        npm install --save-dev eslint-config-airbnb-base@15.0.0 eslint@^8.2.0 eslint-plugin-import@^2.25.2

    - name: Run backend ESLint
      run: |
        cd backend
        npm run lint


    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: Run frontend ESLint
      run: |
        cd frontend
        npm run lint

    - name: Run frontend tests
      run: |
        cd frontend
        npm test