# .github/workflows/main.yml

name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Use the version of Node.js that you're using in your project
    
    - name: Install root ESLint dependencies
      run: |
        npm install --save-dev eslint-config-airbnb-base@15.0.0 eslint@^8.2.0 eslint-plugin-import@^2.25.2 --legacy-peer-deps

    - name: Run root ESLint
      run: |
        npm run lint

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: Run frontend ESLint
      run: |
        cd frontend
        npm run lint -- --config ../.eslintrc.js

    - name: Run tests
      run: |
        cd frontend
        npm test